CREATE DATABASE HeThongChat;
GO
USE HeThongChat;
GO

CREATE TABLE TaiKhoan (
    Id INT PRIMARY KEY IDENTITY(1,1),
    TenDangNhap NVARCHAR(50) UNIQUE NOT NULL,
    MatKhau NVARCHAR(255) NOT NULL,
    NgayTao DATETIME DEFAULT GETDATE()
)

CREATE TABLE LichSuChat (
    Id INT PRIMARY KEY IDENTITY(1,1),
    NguoiGui NVARCHAR(50) NOT NULL,
    NoiDung NVARCHAR(MAX) NOT NULL,
    ThoiGian DATETIME DEFAULT GETDATE()
)